### ISSUE TITLE
[Feature] Sylius 1.11 compatibility

### ISSUE THREAD

**Issue by danakil** [synolia/SyliusMaintenancePlugin#16]
Hello, and thank you for this plugin !

**Is your feature request related to a problem? Please describe.**
I can't install this plugin because my project use Sylius 1.11 ("sylius/sylius": "^1.11").

Problem 1
    - Root composer.json requires synolia/sylius-maintenance-plugin ^1.1 -> satisfiable by synolia/sylius-maintenance-plugin[v1.1.0].
    - synolia/sylius-maintenance-plugin v1.1.0 requires sylius/sylius ~1.9.0 || ~1.10.0 -> found sylius/sylius[v1.9.0, ..., v1.10.14] but it conflicts with your root composer.json require (^1.11).

**Describe the solution you'd like**
The plugin should support Sylius 1.11

**Comment by oallain** [comment]
Hello @danakil 

I've just release [v1.2.0](https://github.com/synolia/SyliusMaintenancePlugin/releases/tag/v1.2.0) with Sylius 1.11 support.

You can now use it.
Regards
