### ISSUE TITLE
[Feature] Allow access to search bots

### ISSUE THREAD

**Issue by MaRecolteBio** [synolia/SyliusMaintenancePlugin#26]
I would like to be able to grant access to search bots during active maintenance to avoid negative impact on SEO score.

**Comment by oallain** [comment]
Hello,

Thanks for your feedback.
Would you want to solve this issue with a PR proposal?

Regards

**Comment by MaRecolteBio** [comment]
I don't have a PR to provide, if I come with something I'll let you know.

**Comment by MaRecolteBio** [comment]
Hello,

It can be solved by changing function isMaintenance in ipChecker.php as follow

```php
public function isMaintenance(MaintenanceConfiguration $configuration, Request $request): bool
    {
        $authorizedIps = $configuration->getArrayIpsAddresses();

        // Check if the request is made by a search engine bot
        $userAgent = $request->headers->get('User-Agent');
        $isSearchBot = preg_match('/bot|crawl|slurp|spider/i', $userAgent);

        if (in_array($request->getClientIp(), $authorizedIps, true) || $isSearchBot) {
            return IsMaintenanceVoterInterface::ACCESS_GRANTED;
        }

        return IsMaintenanceVoterInterface::ACCESS_DENIED;
    }
```

**Comment by oallain** [comment]
Hello,

IMO, overriding the IpChecker is not the right way to do it.
I think we need to:
* Add a configuration on the BO page to allow/block bots
* Create a BotChecker, which will allow access if the browser is detected as a bot.
* Modify the IsMaintenanceVoter to use the BotChecker only if the option is activated

Regards

**Comment by MaRecolteBio** [comment]
Thank you !
